export default [
    'TAGS_ERROR',
    'TAGS_PENDING',
    'TAGS_FETCHED',
    'RECIPE_ERROR',
    'RECIPE_PENDING',
    'RECIPE_FETCHED',
    'INGREDIENTS_ERROR',
    'INGREDIENTS_PENDING',
    'INGREDIENTS_FETCHED',
    'ADDING_INGREDIENT_ERROR',
    'ADDING_INGREDIENT_PENDING',
    'ADDING_INGREDIENT_FETCHED'
];