export default [
    'RECIPE_PENDING',
    'RECIPE_FETCHED',
    'RECIPE_ERROR',
    'INGREDIENTS_PENDING',
    'INGREDIENTS_FETCHED',
    'INGREDIENTS_ERROR',
    'ADDING_INGREDIENT_PENDING',
    'ADDING_INGREDIENT_FETCHED',
    'ADDING_INGREDIENT_ERROR'
];